apiVersion: v1
kind: Service
metadata:
  name: serving-service
  annotations:
    prometheus.io/scrape: "true" 
    prometheus.io/path: "metrics" 
    prometheus.io/port: "9000" 
spec:
  selector:
    app: serving
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 8000
      nodePort: 30080 
    - name: prometheus
      protocol: TCP
      port: 9090
      targetPort: 9090
      nodePort: 30090
  type: NodePort