apiVersion: batch/v1
kind: Job
metadata:
  name: training-job
spec:
  template:
    metadata:
      labels:
        app: training
    spec:
      containers:
      - name: training-container
        image: carlosrosado/training-edo-image:latest
        command: ["python", "/app/src/pipeline/pipeline_mlflow.py"]
        envFrom:
        - configMapRef:
            name: mlflow-config
        resources:
          requests:
            memory: "512Mi"
            cpu: "500m"
          limits:
            memory: "1Gi"
            cpu: "1"
      restartPolicy: Never
  backoffLimit: 4